# Generated by Django 5.2.1 on 2025-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoArtesanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('impacto_social', models.TextField(blank=True)),
                ('hash_blockchain', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
