# Generated by Django 5.2.1 on 2025-06-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoartesanal',
            name='confianza_ia',
            field=models.FloatField(default=0.0),
        ),
    ]
