# Generated by Django 5.2.1 on 2025-06-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productoartesanal_confianza_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoartesanal',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
